steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west3-docker.pkg.dev/black-pearl-334121/mwieser/tarent-loginsrv:$COMMIT_SHA', '--target', 'app', '.' ]
images:
- 'europe-west3-docker.pkg.dev/black-pearl-334121/mwieser/tarent-loginsrv:$COMMIT_SHA'